function [modifiedclDistro] = ModifiedCLDistro( ...
    clDistroSpanTO, ...
    etaDistro, ...
    ComplexSectionEta, ...
    clAlphaDistro, ...
    etaBeginFlap, ...
    etaEndFlap, ...
    etaBeginSlat, ...
    etaEndSlat, ...
    alphaDelta, ...
    cPrimeOverCFlap, ...
    deltaFlaps, ...
    HingeLineSweep, ...
    cOvercref, ...
    clDeltaSlatDesign, ...
    deltaSlats, ...
    cPrimeOverCSlat, ...
    LeadingEdgeSweep ...
    )

    modifiedclDistro = clDistroSpanTO;

    for k = 1:length(etaDistro)
                
        etaK = etaDistro(k);
        sectionIdx = find(etaK <= ComplexSectionEta, 1, 'first');

        if isempty(sectionIdx)
            sectionIdx = length(ComplexSectionEta);
        end

        clAlphaK = clAlphaDistro(sectionIdx);
    
        if etaK >= etaBeginFlap && etaK <= etaEndFlap
            
            deltaclFlap = ...
                clAlphaK * alphaDelta * cPrimeOverCFlap ...
                * (deltaFlaps * (pi / 180));
            
            modifiedclDistro(k) = modifiedclDistro(k) + ...
                deltaclFlap * cosd(HingeLineSweep(k)) * cOvercref(k);
        end
    
        if etaK >= etaBeginSlat && etaK <= etaEndSlat
            
            deltaclSlat = ...
                clDeltaSlatDesign * (deltaSlats * (pi / 180)) * ...
                cPrimeOverCSlat;
            
            modifiedclDistro(k) = modifiedclDistro(k) + ...
                deltaclSlat * cosd(LeadingEdgeSweep(k)) * cOvercref(k);
        end
    end

end